### ISSUE TITLE
[Chrome] AudioParam will be deprecated around March 2018

### ISSUE THREAD

**Issue by typerror** [processing/p5.js-sound#255] opened 2018-02-23 00:13 UTC
X --> Console Error
[Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.

**Comment by aksperiod** [comment] 2018-02-27 03:26
I was able to get rid of these errors by replacing the `this.biquad.frequency.value = freq` to `this.biquad.frequency.setTargetAtTime(freq, time)`. It looked like it removed the need for some of the other event-cancelling code. The other change needed to fix is changing `this.limiter.threshold.value` and `p5.soundOut._silentNode.gain.value` to use `setValueAtTime()` instead of directly setting the value. Here is the documentation: https://developer.mozilla.org/en-US/docs/Web/API/AudioParam, however I don't know enough about this library to feel confident in patching.

**Comment by therewasaguy** [comment] 2018-02-27 03:45
thanks @aksperiod and @typerror ! This is a duplicate of https://github.com/processing/p5.js-sound/issues/233

It will be good to update (especially to get rid of console warnings) but isn't breaking anything or changing any functionality.

> we've avoided assigning values directly after using scheduling methods, so this shouldn't cause any issues.

At one point I started looking at refactoring all the audio param value scheduling so that this could be more consistent throughout the library and changed in one place. Something like this over [here](https://github.com/therewasaguy/p5.js-sound/commit/7b42d2512ccb013d7a4a5c9df562e3cde1e5321d#diff-258bea0fe67808263ed433fbac4f7762). Any feedback on that idea and/or pr's would be welcome!

**Closed by therewasaguy** 2018-02-27 03:45 UTC
