### ISSUE TITLE
p5.SoundFile.setVolume issue

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#169] opened 2017-04-30 00:58 UTC
_From @dairbuirabass on April 28, 2017 19:29_

After setting volume and calling play() in draw again, it resets volume to default (1.0). 
I know there should be some ways of avoiding it, but still should it count as an issue?

_Copied from original issue: processing/p5.js#1918_

**Comment by b2renger** [comment] 2017-04-30 12:54
@dairbuirabass, it's hard to tell if it is really an issue from the elements you give. What are you trying to achieve exactly ?  and could you post a small example with code ?

Are you talking about the setVolume from the p5.SoundFile class : https://p5js.org/reference/#/p5.SoundFile/setVolume

or the masterVolume  : https://p5js.org/reference/#/p5.sound/masterVolume

**Comment by dairbuirabass** [comment] 2017-05-13 21:29
Yes, I mean the SoundFile class, pardon.
So basically, when I initialize the SoundFile object

```
function preload()
{	
	menu_music = loadSound('sounds/chinese_stock_car_dealer.ogg');	
}
```
Then I set the volume
function setup()

```
{
	menu_music.setVolume(0.1);
}
```

And there is no effect neither if I play it right away in setup, nor if I loop it in draw.

I guess it is just me not handling functions correctly, but just in case.

**Comment by therewasaguy** [comment] 2017-06-28 12:40
duplicate of https://github.com/processing/p5.js-sound/issues/182 and I'll close this one as https://github.com/processing/p5.js-sound/issues/182 has some more discussion and seems close to a solution

**Closed by therewasaguy** 2017-06-28 12:40 UTC

**Comment by dairbuirabass** [comment] 2017-06-28 17:24
@therewasaguy Thanks
